/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   using_printf.c                                     :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: smodesto <smodesto@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/06/17 10:44:29 by smodesto          #+#    #+#             */
/*   Updated: 2021/06/30 17:04:19 by smodesto         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include "using_printf.h"

int	main(void)
{
	printf("\n");
	printf(ANSI_YELLOW);
	printf("---------------------------------------------------------------\n");
	printf("---------------------PRINTF FLAGS TEST-------------------------\n");
	printf("---------------------------------------------------------------\n");
	printf("\n");
	printf("\n");
	printf("--------------------------Character-----------------------------\n");
	printf(ANSI_RESET);
	printf("\n");
	printf("%-60s: |%c|", "format identifier", 'x');
	printf("\n");
	printf("%-60s: |%-20c|", "minimum field (20) left align", 'x');
	printf("\n");
	printf("%-60s: |%-*c|", "minimum (8) field(*) left align", 8,'x');
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("--------------------------String--------------------------------\n");
	printf(ANSI_RESET);
	printf("%-60s: |%s|", "format identifier", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%20s|", "with minimum field (20) width", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%-20s|", "minimum field (20) left-align", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%.8s|", "precision (8) field", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%-.8s|", "precision(8) field left-align", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%20.8s|", "minimum (20) and precision (8) field", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%-20.8s|", "minimum (20) and precision (8) field left align", "Quarante-deux");
	printf("\n");
	printf("%-60s: |%-*.*s|", "minimum (20) and precision (8) field left align",20, 8, "Quarante-deux");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("---------------------------------------------pointer----------------------------------------------------\n");
	printf(ANSI_RESET);
	printf("\n");

	int *pointer;
	int num;

	num = 42;
	pointer = &num;
	printf("%-60s: |%p|","format identifier", pointer);
	printf("\n");
	printf("%-60s: |%20p|", "with minimum field (20) width", pointer);
	printf("\n");
	printf("%-60s: |%-20p|\n", "minimum field (20) left align", pointer);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("----------------------------------------decimal_signed_integer---------------------------------------------\n");
	printf(ANSI_RESET);
	printf("\n");
	int hex_neg = -0x2a;

	printf("%-60s: |%d|","format identifier", -42);
	printf("\n");
	printf("%-60s: |%d|","(hex) format identifier", hex_neg);
	printf("\n");
	printf("%-60s: |%-3d|", "with minimum field (3) width", -42);
	printf("\n");
	printf("%-60s: |%5d|", "with minimum field (5) width", -42);
	printf("\n");
	printf("%-60s: |%05d|", "with minimum field (5) width and 0 padding", -42);
	printf("\n");
	printf("%-60s: |%5.3d|", "minimum field (5) width with 0's", -42);
	printf("\n");
	printf("%-60s: |%-5d|", "minimum field (5) left align", -42);
	printf("\n");
	printf("%-60s: |%5.1d|", "precision (1) and minimum (5) field", -42);
	printf("\n");
	printf("%-60s: |%.3d|", "precision (3) field", hex_neg);
	printf("\n");
	printf("%-60s: |%-.5d|", "precision (5) field left align", hex_neg);
	printf("\n");
	printf("%-60s: |%10.5d|", "minimum (10) and precision (5) field", -42);
	printf("\n");
	printf("%-60s: |%-10.5d|", "minimum (10) and precision (5) field left align", -42);
	printf("\n");
	printf("%-60s: |%-*.*d|", "minimum (20) and precision (1) field left align", 20, 1, hex_neg);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("-----------------------------------------------integer--------------------------------------------------------\n");
	printf(ANSI_RESET);
	printf("\n");
	printf("%-60s: |%i|","format identifier", -42);
	printf("\n");
	printf("%-60s: |%20i|", "with minimum field (20) width", -42);
	printf("\n");
	printf("%-60s: |%020i|", "minimum field (20) width with 0's", -42);
	printf("\n");
	printf("%-60s: |%-20i|", "minimum field (20) left align", -42);
	printf("\n");
	printf("%-60s: |%20.1i|", "precision (1) and minimum (20) field", -42);
	printf("\n");
	printf("%-60s: |%.1i|", "precision (1) field", -42);
	printf("\n");
	printf("%-60s: |%-.1i|", "(hex_neg) precision (1) field left align", hex_neg);
	printf("\n");
	printf("%-60s: |%020.10i|", "minimum (20) and precision (10) field", -12345678);
	printf("\n");
	printf("%-60s: |%-20.10i|", "minimum (20) and precision (10) field left align", -12345678);
	printf("\n");
	printf("\n");
	printf("%-60s: |%-*.*i|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, hex_neg);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("-------------------------------------------unsigned_integer------------------------------------------------------\n");
	printf(ANSI_RESET);
	printf("\n");
	printf(ANSI_RED);
	printf("%-60s: |%u|","negative input", -42);
	printf(ANSI_RESET);
	printf("\n");
	printf("%-60s: |%u|","format identifier", 42);
	printf("\n");
	printf("%-60s: |%20u|", "with minimum field (20) width", 42);
	printf("\n");
	printf("%-60s: |%020u|", "minimum field (20) width with 0's", 42);
	printf("\n");
	printf("%-60s: |%-20u|", "minimum field (20) left align", 42);
	printf("\n");
	printf("%-60s: |%20.1u|", "precision (1) and minimum (20) field", 42);
	printf("\n");
	printf("%-60s: |%.1u|", "precision (1) field", 42);
	printf("\n");
	printf("%-60s: |%-.1u|", "(hex_neg) precision (1) field left align", 42);
	printf("\n");
	printf("%-60s: |%-20.1u|", "minimum (20) and precision (1) field left align", 42);
	printf("\n");
	printf("%-60s: |%-*.*u|", "(hex_neg) minimum (20) and precision (1) field left align", 20, 1, 42);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("---------------------------------------------hex_integer_lowercase----------------------------------------------------\n");
	printf(ANSI_RESET);

	int hex = 0x9f4;
	int integer = 42;

	printf("\n");
	printf("%-60s: |%x|","(int) format identifier", integer);
	printf("\n");
	printf("%-60s: |%x|","(hex) format identifier", hex);
	printf("\n");
	printf("%-60s: |%20x|", "(int) with minimum field (20) width", integer);
	printf("\n");
	printf("%-60s: |%20x|", "(hex) with minimum field (20) width", hex);
	printf("\n");
	printf("%-60s: |%020x|", "(int) minimum field (20) width with 0's", integer);
	printf("\n");
	printf("%-60s: |%020x|", "(hex) minimum field (20) width with 0's", hex);
	printf("\n");
	printf("%-60s: |%-20x|", "(int) minimum field (20) left align", integer);
	printf("\n");
	printf("%-60s: |%-20x|", "(hex) minimum field (20) left align", hex);
	printf("\n");
	printf("%-60s: |%20.6x|", "precision (6) and minimum (20) field", hex);
	printf("\n");
	printf("%-60s: |%.6x|", "precision (6) field", integer);
	printf("\n");
	printf("%-60s: |%-.6x|", "(hex_neg) precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-20.6x|", "minimum (20) and precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-*.*x|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("---------------------------------------------hex_integer_uppercase----------------------------------------------------\n");
	printf(ANSI_RESET);
	printf("\n");
	printf("%-60s: |%X|","(int) format identifier", integer);
	printf("\n");
	printf("%-60s: |%X|","(hex) format identifier", hex);
	printf("\n");
	printf("%-60s: |%20X|", "(int) with minimum field (20) width", integer);
	printf("\n");
	printf("%-60s: |%20X|", "(hex) with minimum field (20) width", hex);
	printf("\n");
	printf("%-60s: |%020X|", "(int) minimum field (20) width with 0's", integer);
	printf("\n");
	printf("%-60s: |%020X|", "(hex) minimum field (20) width with 0's", hex);
	printf("\n");
	printf("%-60s: |%-20X|", "(int) minimum field (20) left align", integer);
	printf("\n");
	printf("%-60s: |%-20X|", "(hex) minimum field (20) left align", hex);
	printf("\n");
	printf("%-60s: |%20.6X|", "precision (6) and minimum (20) field", hex);
	printf("\n");
	printf("%-60s: |%.6X|", "precision (6) field", integer);
	printf("\n");
	printf("%-60s: |%-.6X|", "(hex_neg) precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-20.6X|", "minimum (20) and precision (6) field left align", hex);
	printf("\n");
	printf("%-60s: |%-*.*X|", "(hex_neg) minimum (20) and precision (6) field left align", 20, 6, hex);
	printf("\n");
	printf("\n");
	printf("\n");
	printf("\n");
	printf(ANSI_YELLOW);
	printf("--------------------------------------------------------%%---------------------------------------------------------------\n");
	printf(ANSI_RESET);
	printf("|%0%|");
	printf("\n");
	printf("|%5%|");
	printf("\n");
	printf("|%0.5%|");
	printf("\n");
	printf("|%-10.4%|");
	printf("\n");
	printf("\n");
	printf("\n");
	return (0);
}
